In [26]:
import pandas as pd
import numpy as np

n = int(input('Enter the number of transactions: '))
transactions = []
for i in range(n):
    transactions.append(list(map(str, input(f'Enter the items in transaction {i+1}:').split(','))))

def calculate_metrics(antecedent, consequent, transactions):
    count  = count_antecedent = count_consequent = 0
    for transaction in transactions:
        if set(antecedent).issubset(transaction):
            count_antecedent += 1
        if set(consequent).issubset(transaction):
            count_consequent += 1
        if set(antecedent).issubset(transaction) and set(consequent).issubset(transaction):
            count += 1
    support_antecedent = float(count_antecedent)/n
    support_consequent = float(count_consequent)/n
    support = float(count)/n
    confidence = float(count)/count_antecedent
    lift = support/(support_antecedent*support_consequent)
    return (support, confidence, lift)

ant = ['A']
cons = ['D']
calculate_metrics(ant, cons, transactions)

Enter the number of transactions:  5
Enter the items in transaction 1: A,B,C
Enter the items in transaction 2: A,C,D
Enter the items in transaction 3: B,C,D
Enter the items in transaction 4: A,D,E
Enter the items in transaction 5: B,C,E

(0.4, 0.6666666666666666, 1.1111111111111112)

In [2]:
import numpy as np
import pandas as pd

n = int(input('Enter the number of transactions: '))
transactions = []

for i in range(n):
    transactions.append(list(map(str, input(f'Enter the elements of transaction {i+1}').split(','))))

def calculate_metrics(antecedent, consequent, transactions):
    count = count_antecedent = count_consequent = 0
    for transaction in transactions:
        if set(antecedent).issubset(transaction) and set(consequent).issubset(transaction):
            count += 1
        if set(antecedent).issubset(transaction):
            count_antecedent += 1
        if set(consequent).issubset(transaction):
            count_consequent += 1
            
    support_antecedent = float(count_antecedent)/n
    support_consequent = float(count_consequent)/n
    support = float(count)/n
    confidence = float(count)/count_antecedent
    lift = float(count)/(count_antecedent*count_consequent)
    return (support, confidence, lift)

ant = ['B', 'C']
cons = ['A']
calculate_metrics(ant, cons, transactions)

Enter the number of transactions:  5
Enter the elements of transaction 1 A,B,C
Enter the elements of transaction 2 A,C,D
Enter the elements of transaction 3 B,C,D
Enter the elements of transaction 4 A,D,E
Enter the elements of transaction 5 B,C,E

(0.2, 0.3333333333333333, 0.1111111111111111)

In [10]:
foo = pd.read_csv('market_basket_optimisation.csv')
foo

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
transactions = foo.values.tolist()
import numpy as np
import pandas as pd

def calculate_metrics(antecedent, consequent, transactions):
    count = count_antecedent = count_consequent = 0
    for transaction in transactions:
        if set(antecedent).issubset(transaction) and set(consequent).issubset(transaction):
            count += 1
        if set(antecedent).issubset(transaction):
            count_antecedent += 1
        if set(consequent).issubset(transaction):
            count_consequent += 1
            
    support_antecedent = float(count_antecedent)/len(transactions)
    support_consequent = float(count_consequent)/len(transactions)
    support = float(count)/len(transactions)
    confidence = float(count)/count_antecedent
    lift = float(count)/(count_antecedent*count_consequent)
    return (support, confidence, lift)

In [17]:
antecedent = ['shrimp']
consequent = ['olive oil']
calculate_metrics(antecedent, consequent, transactions)

(0.0076, 0.11046511627906977, 0.00023304876852124422)

In [18]:
antecedent = ['turkey']
consequent = ['burgers']
calculate_metrics(antecedent, consequent, transactions)

(0.010133333333333333, 0.16851441241685144, 0.00026790844581375426)

In [19]:
antecedent = ['honey', 'milk']
consequent = ['protein bar']
calculate_metrics(antecedent, consequent, transactions)

(0.0008, 0.10344827586206896, 0.0007836990595611285)